spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/girl?characterEncoding=utf8&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8082
#  context-path: /girl
girl:
  cupSize: B
  six: 18